# Build and run the application as defualt.
defualt: build run

# Build the application.
build:
	@g++ main1.cpp -o main -Wall -Werror

# Run the application.
run:
	@./main

# Clean the application.
clean:
	@rm -f main



